# Generated by Django 4.2.11 on 2024-06-15 19:24

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the Language name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Enter the language code", max_length=5),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="BookInstance",
            new_name="LibraryCopy",
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_name_case_insensitive_unique",
                violation_error_message="Language already exists (case insensitive match)",
            ),
        ),
    ]
