# Generated by Django 4.2.11 on 2024-06-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_rename_bookinstance_librarycopy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.book",
            ),
        ),
    ]
